"""Typed contracts exported for adapters and application consumers."""

from curupira.models.azure import (
    AzHref,
    AzPullRequest,
    AzPullRequestLinks,
    AzPullRequestSearchRequest,
    AzurePullRequestStatus,
)
from curupira.models.configuration import (
    AutomationConfiguration,
    AzurePullRequestAutomationConfiguration,
    CodingAgentDefaults,
    CodingAgentsSettings,
    CronAutomationConfiguration,
    ExecutionSettings,
    IssueAutomationConfiguration,
    MondayAutomationConfiguration,
    PollingSettings,
    PullRequestAutomationConfiguration,
    TrelloAutomationConfiguration,
)
from curupira.models.github import (
    DEFAULT_ISSUE_JSON_FIELDS,
    GhIssue,
    GhIssueSearchRequest,
    GhLabel,
    GhPullRequest,
    GhPullRequestSearchRequest,
)
from curupira.models.process import (
    CodingTaskRequest,
    CommandRequest,
    DispatchOutcome,
    ProcessResult,
)
from curupira.models.profiles import (
    ClaudeCodeCliProfile,
    CliProfile,
    CliProfileBase,
    CodexCliProfile,
    CursorCliProfile,
    OpenCodeCliProfile,
)
from curupira.models.tasks import (
    CronRunState,
    ResolvedAutomation,
    RunningCodingSession,
    Task,
    TaskIdentity,
)
from curupira.models.trello import TrelloBoard, TrelloCard, TrelloList, TrelloListRequest

__all__ = [
    "DEFAULT_ISSUE_JSON_FIELDS",
    "AutomationConfiguration",
    "AzHref",
    "AzPullRequest",
    "AzPullRequestLinks",
    "AzPullRequestSearchRequest",
    "AzurePullRequestAutomationConfiguration",
    "AzurePullRequestStatus",
    "ClaudeCodeCliProfile",
    "CliProfile",
    "CliProfileBase",
    "CodexCliProfile",
    "CodingAgentDefaults",
    "CodingAgentsSettings",
    "CodingTaskRequest",
    "CommandRequest",
    "CronAutomationConfiguration",
    "CronRunState",
    "CursorCliProfile",
    "DispatchOutcome",
    "ExecutionSettings",
    "GhIssue",
    "GhIssueSearchRequest",
    "GhLabel",
    "GhPullRequest",
    "GhPullRequestSearchRequest",
    "IssueAutomationConfiguration",
    "MondayAutomationConfiguration",
    "OpenCodeCliProfile",
    "PollingSettings",
    "ProcessResult",
    "PullRequestAutomationConfiguration",
    "ResolvedAutomation",
    "RunningCodingSession",
    "Task",
    "TaskIdentity",
    "TrelloAutomationConfiguration",
    "TrelloBoard",
    "TrelloCard",
    "TrelloList",
    "TrelloListRequest",
]
